import 'package:flutter/material.dart';
import 'package:music/assets.dart';
import 'package:music/models/music.dart';

final List<Content> music = const [
  Content(
    id: 0,
    name: "Duniya",
    audioUrl: Assets.duniya_audiourl,
    imageUrl: Assets.duniya_imageurl,
    color: Colors.orange,
    category: "Pop",
    movie: "Luka Chupi",
  ),
  Content(
    id: 1,
    name: "Raanjhana",
    audioUrl: Assets.raanjhana_audiourl,
    imageUrl: Assets.raanjhana_imageurl,
    color: Colors.red,
    category: "Pop",
    movie: "Raanjhana",
  ),
  Content(
    id: 2,
    name: "Pyaar k Pal",
    audioUrl: Assets.pyaar_audiourl,
    imageUrl: Assets.pyaar_imageurl,
    color: Colors.yellow,
    category: "Pop",
    movie: "Dosti",
  ),
  Content(
    id: 3,
    name: "Adaat",
    audioUrl: Assets.adaat_audiourl,
    imageUrl: Assets.adaat_imageurl,
    color: Colors.green,
    category: "Pop",
    movie: "Kalyug",
  ),
  Content(
    id: 4,
    name: "Kabhi Kabhi Aditi",
    audioUrl: Assets.aditi_audiourl,
    imageUrl: Assets.aditi_imageurl,
    color: Colors.blue,
    category: "Pop",
    movie: "Jane tu Ya Jane Na ",
  ),
  Content(
    id: 5,
    name: "Ghungroo",
    audioUrl: Assets.ghungroo_audiourl,
    imageUrl: Assets.ghungroo_imageurl,
    color: Colors.purple,
    category: "Pop",
    movie: "War",
  ),
  Content(
    id: 6,
    name: "Teri Zhuki Nazar",
    audioUrl: Assets.jiya_audiourl,
    imageUrl: Assets.jiya_imageurl,
    color: Colors.indigo,
    category: "Pop",
    movie: "Murder 3",
  ),
  Content(
    id: 7,
    name: "Jai Jai Shiv Shankar",
    audioUrl: Assets.shiv_audiourl,
    imageUrl: Assets.shiv_imageurl,
    color: Colors.red,
    category: "Pop",
    movie: "War",
  ),
  Content(
    id: 8,
    name: "Baarish ",
    audioUrl: Assets.baarish_audiourl,
    imageUrl: Assets.baarish_imageurl,
    color: Colors.white,
    category: "Pop",
    movie: "Yeh Hai Yaariyan",
  ),
  Content(
    id: 9,
    name: "Meri Maa",
    audioUrl: Assets.maa_audiourl,
    imageUrl: Assets.maa_imageurl,
    color: Colors.cyan,
    category: "Pop",
    movie: "Yeh Hai Yaariyan",
  ),
  Content(
    id: 10,
    name: "Badal Pe Paon Hai",
    audioUrl: Assets.badal_audiourl,
    imageUrl: Assets.badal_imageurl,
    color: Colors.blueGrey,
    category: "Pop",
    movie: "Chak De India",
  ),
  Content(
    id: 11,
    name: "Senorita",
    audioUrl: Assets.seno_audiourl,
    imageUrl: Assets.seno_imageurl,
    color: Colors.orangeAccent,
    category: "Pop",
    movie: "Senorita",
  ),
  Content(
    id: 12,
    name: "Jaadu Teri Nazar",
    audioUrl: Assets.jadoo_audiourl,
    imageUrl: Assets.jadoo_imageurl,
    color: Colors.yellow,
    category: "Pop",
    movie: "Darr",
  ),
  Content(
    id: 13,
    name: "Shukran Allah",
    audioUrl: Assets.shukran_audiourl,
    imageUrl: Assets.shukran_imageurl,
    color: Colors.deepOrange,
    category: "Pop",
    movie: "Kurban",
  ),
  Content(
    id: 14,
    name: "Chori Kiya re Jiya",
    audioUrl: Assets.chori_audiourl,
    imageUrl: Assets.chori_imageurl,
    color: Colors.deepPurple,
    category: "Pop",
    movie: "Dabangg",
  ),
  Content(
    id: 15,
    name: "Tera Yaar Hoon mai",
    audioUrl: Assets.dekha_audiourl,
    imageUrl: Assets.dekha_imageurl,
    color: Colors.blueAccent,
    category: "Pop",
    movie: "Sonu Ki Titu ki Sweety",
  ),
  Content(
    id: 16,
    name: "Baarish Ban jana ",
    audioUrl: Assets.ban_audiourl,
    imageUrl: Assets.ban_imageurl,
    color: Colors.redAccent,
    category: "Pop",
    movie: "Baarish Ban Jana ",
  ),
  Content(
    id: 17,
    name: "Chak De India",
    audioUrl: Assets.chak_audiourl,
    imageUrl: Assets.chak_imageurl,
    color: Colors.pink,
    category: "Pop",
    movie: "Chak De India",
  ),
  Content(
    id: 18,
    name: "Breathless",
    audioUrl: Assets.breathe_audiourl,
    imageUrl: Assets.breathe_imageurl,
    color: Colors.black,
    category: "Pop",
    movie: "Breatheless",
  ),
  Content(
    id: 19,
    name: "Wakka Wakka",
    audioUrl: Assets.girls_audiourl,
    imageUrl: Assets.girls_imageurl,
    color: Colors.lightGreenAccent,
    category: "Pop",
    movie: "FIFA World Cup",
  ),
  Content(
    id: 20,
    name: "Yeh Dooriyan",
    audioUrl: Assets.kabhi_audiourl,
    imageUrl: Assets.kabhi_imageurl,
    color: Colors.cyan,
    category: "Pop",
    movie: "Love Aaj Kal",
  ),
  Content(
    id: 21,
    name: "Abhi Kuch Dino se",
    audioUrl: Assets.bheegi_audiourl,
    imageUrl: Assets.bheegi_imageurl,
    color: Colors.greenAccent,
    category: "Pop",
    movie: "Dil To Baccha hai ji",
  ),
  Content(
    id: 22,
    name: "Tune Jo na kahan",
    audioUrl: Assets.tune_audiourl,
    imageUrl: Assets.tune_imageurl,
    color: Colors.cyanAccent,
    category: "Pop",
    movie: "New York",
  ),
  Content(
    id: 23,
    name: "Aao Milo Chale",
    audioUrl: Assets.aao_audiourl,
    imageUrl: Assets.aao_imageurl,
    color: Colors.indigoAccent,
    category: "Pop",
    movie: "Jab We Met",
  ),
  Content(
    id: 24,
    name: "Shape Of You",
    audioUrl: Assets.shape_audiourl,
    imageUrl: Assets.shape_imageurl,
    color: Colors.pinkAccent,
    category: "Pop",
    movie: "Shape Of You",
  ),
  Content(
    id: 25,
    name: "Senorita",
    audioUrl: Assets.senor_audiourl,
    imageUrl: Assets.senor_imageurl,
    color: Colors.white54,
    category: "Pop",
    movie: "Zindagi Na Milegi Dobara",
  ),
  Content(
    id: 26,
    name: "Khuda Bhi Jab Tumhe",
    audioUrl: Assets.happy_audiourl,
    imageUrl: Assets.happy_imageurl,
    color: Colors.lightBlue,
    category: "Pop",
    movie: "Ek Pehi Leela",
  ),
  Content(
    id: 27,
    name: "Kun Faya Kun",
    audioUrl: Assets.dheere_audiourl,
    imageUrl: Assets.dheere_imageurl,
    color: Colors.orangeAccent,
    category: "Pop",
    movie: "RockStar",
  ),
  Content(
    id: 28,
    name: "Memories",
    audioUrl: Assets.memo_audiourl,
    imageUrl: Assets.memo_imageurl,
    color: Colors.brown,
    category: "Pop",
    movie: "Maroon 5",
  ),
  Content(
    id: 29,
    name: "Give Me some sunshine ",
    audioUrl: Assets.idiot_audiourl,
    imageUrl: Assets.idiot_imageurl,
    color: Colors.purpleAccent,
    category: "Pop",
    movie: "3 Idiots",
  ),
];
